-- Add meet_link column to consultations table
-- This column stores the Google Meet conference link for each consultation

-- Add the column
ALTER TABLE consultations 
ADD COLUMN IF NOT EXISTS meet_link TEXT;

-- Add comment to document the column
COMMENT ON COLUMN consultations.meet_link IS 'Google Meet conference link for the consultation (generated by Google Calendar API)';

-- Create index for faster lookups when displaying consultations with meet links
CREATE INDEX IF NOT EXISTS idx_consultations_meet_link ON consultations(meet_link) 
WHERE meet_link IS NOT NULL;

-- Verify the change
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'consultations' 
AND column_name = 'meet_link';
